/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SchedulesIndexRouteImport } from './routes/schedules/index'
import { Route as HostsIndexRouteImport } from './routes/hosts/index'
import { Route as ActorsIndexRouteImport } from './routes/actors/index'
import { Route as ActorsTypeIdRouteImport } from './routes/actors/$type/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulesIndexRoute = SchedulesIndexRouteImport.update({
  id: '/schedules/',
  path: '/schedules/',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsIndexRoute = HostsIndexRouteImport.update({
  id: '/hosts/',
  path: '/hosts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActorsIndexRoute = ActorsIndexRouteImport.update({
  id: '/actors/',
  path: '/actors/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActorsTypeIdRoute = ActorsTypeIdRouteImport.update({
  id: '/actors/$type/$id',
  path: '/actors/$type/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actors/': typeof ActorsIndexRoute
  '/hosts/': typeof HostsIndexRoute
  '/schedules/': typeof SchedulesIndexRoute
  '/actors/$type/$id': typeof ActorsTypeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actors': typeof ActorsIndexRoute
  '/hosts': typeof HostsIndexRoute
  '/schedules': typeof SchedulesIndexRoute
  '/actors/$type/$id': typeof ActorsTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actors/': typeof ActorsIndexRoute
  '/hosts/': typeof HostsIndexRoute
  '/schedules/': typeof SchedulesIndexRoute
  '/actors/$type/$id': typeof ActorsTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/actors/' | '/hosts/' | '/schedules/' | '/actors/$type/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/actors' | '/hosts' | '/schedules' | '/actors/$type/$id'
  id:
    | '__root__'
    | '/'
    | '/actors/'
    | '/hosts/'
    | '/schedules/'
    | '/actors/$type/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActorsIndexRoute: typeof ActorsIndexRoute
  HostsIndexRoute: typeof HostsIndexRoute
  SchedulesIndexRoute: typeof SchedulesIndexRoute
  ActorsTypeIdRoute: typeof ActorsTypeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedules/': {
      id: '/schedules/'
      path: '/schedules'
      fullPath: '/schedules/'
      preLoaderRoute: typeof SchedulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts/': {
      id: '/hosts/'
      path: '/hosts'
      fullPath: '/hosts/'
      preLoaderRoute: typeof HostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actors/': {
      id: '/actors/'
      path: '/actors'
      fullPath: '/actors/'
      preLoaderRoute: typeof ActorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actors/$type/$id': {
      id: '/actors/$type/$id'
      path: '/actors/$type/$id'
      fullPath: '/actors/$type/$id'
      preLoaderRoute: typeof ActorsTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActorsIndexRoute: ActorsIndexRoute,
  HostsIndexRoute: HostsIndexRoute,
  SchedulesIndexRoute: SchedulesIndexRoute,
  ActorsTypeIdRoute: ActorsTypeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
